[package]
name = "moemenu"
version = "0.1.0"
authors = ["fence <fence@desu-mail.moe>"]
edition = "2018"
license = "GPL-3+"

[dependencies]
rgb = "0.8.25"
x11 = { version = "2.18.1", features = ["xlib"] }

[dependencies.x11rb]
version = "0.8.0"
features = ["allow-unsafe-code", "render"]

[dependencies.cairo-rs]
version = "0.9"
features = ["xcb"]
