[package]
name = "moemenu"
version = "0.1.0"
authors = ["fence <fence@desu-mail.moe>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.x11rb]
version = "0.8.0"
features = ["allow-unsafe-code", "render"]

[dependencies.cairo-rs]
version = "0.9"
features = ["xcb"]
